[phases.setup]
nixPkgs = ['python311', 'gcc', 'g++']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p model_cache']

[start]
cmd = 'uvicorn main:app --host 0.0.0.0 --port 5001'
